### ISSUE TITLE
session ERROR

### ISSUE THREAD

**Issue by tankle** [whtsky/WeRoBot-SAE-demo#4]
Traceback (most recent call last):
  File "/data1/www/htdocs/810/ddlan/2/index.wsgi", line 2, in <module>
    from robot import robot
  File "/data1/www/htdocs/810/ddlan/2/robot.py", line 14, in <module>
    robot = werobot.WeRoBot(token='tokenhere',enable_session=True)
  File "/data1/www/htdocs/810/ddlan/2/site-packages/werobot/robot.py", line 47, in **init**
    filename=os.path.abspath("werobot_session")
  File "/data1/www/htdocs/810/ddlan/2/site-packages/werobot/session/filestorage.py", line 20, in **init**
    self.db = dbm.open(filename, "c")
  File "/usr/local/sae/python/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "/usr/local/sae/python/lib/python2.7/dumbdbm.py", line 250, in open
    return _Database(file, mode)
  File "/usr/local/sae/python/lib/python2.7/dumbdbm.py", line 71, in __init__
    f = _open(self._datfile, 'w')
IOError: [Errno 13] Permission denied: '/data1/www/htdocs/810/ddlan/2/werobot_session.dat'

这是修改增加了sys.path.insert(1, os.path.join(root, 'Lib/site-packages'))
之后出现的错误。

**Comment by tankle** [comment]
是我的KVD没没打开。不好意思
